"use client";
import { useTranslation } from "@/components/Context/TranslationContext";
import TagPill from "../TagPill/TagPill";

const categories = [
  { key: "raceEthnicity", labelKey: "raceEthnicity" },
  { key: "hairColor", labelKey: "hairColor" },
  { key: "bodyType", labelKey: "bodyType" },
];

export default function AutoGeneratedTagsInfo({ tagsObj, mongoUser }) {
  const { t } = useTranslation();
  // Check if user set any preferences
  const hasUserPref = Boolean(
    mongoUser?.preferAge ||
      mongoUser?.raceEthnicity ||
      mongoUser?.hairColor ||
      mongoUser?.bodyType
  );
  return (
    <div className={`mb-6 block ${hasUserPref ? "" : ""}`}>
      <div className="text-sm text-foreground/80 mb-2">
        {t("autoGeneratedTagsInfo")}
      </div>
      <div className="flex flex-wrap gap-2">
        {/* Only show raceEthnicity if user is Dev */}
        {categories.map(({ key, labelKey }) => {
          if (key === "raceEthnicity" && !mongoUser?.isDev) return null;
          return tagsObj?.[key] ? (
            <TagPill key={key}>
              {t(labelKey)}: {t(tagsObj[key]) || tagsObj[key]}
            </TagPill>
          ) : null;
        })}
      </div>
    </div>
  );
}
