"use client";
import { useRouter } from "next/navigation";
import dynamic from "next/dynamic";
import {
  MAIN_ROUTE,
  MIN_VISITED_CREATOR_TAGS_FOR_SMART_MATCHING,
  ONBOARDING_ROUTE,
} from "@/lib/utils/constants";
import { useTranslation } from "@/components/Context/TranslationContext";
import { getMostFrequentCreatorTags } from "@/lib/utils/getMostFrequentCreatorTags";
import { hasUserPreferences } from "@/lib/utils/hasUserPreferences";
import AutoGeneratedTagsInfo from "@/components/ui/shared/AutoGeneratedTagsInfo/AutoGeneratedTagsInfo";
import ClearAllSuggestionsButton from "@/components/ui/shared/ClearAllSuggestionsButton/ClearAllSuggestionsButton";
import TagProgressBar from "@/components/ui/shared/TagProgressBar/TagProgressBar";
import PreferencesNote from "@/components/ui/shared/PreferencesNote/PreferencesNote";
import CreatorAttributesNote from "@/components/ui/shared/CreatorAttributesNote/CreatorAttributesNote";

const ProfileForm = dynamic(
  () => import("@/app/my/settings/profile/ProfileForm"),
  { ssr: false }
);
const AccountForm = dynamic(
  () => import("@/app/my/settings/account/AccountForm"),
  { ssr: false }
);

export default function OnboardingStep2Client({ mongoUser }) {
  const router = useRouter();
  const { t } = useTranslation();
  const isCreator = mongoUser.profileType === "creator";
  const isFan = mongoUser.profileType === "fan";
  const userHasPreferences = hasUserPreferences(mongoUser);

  const handleSuccess = async () => {
    if (isFan) {
      // Fan goes to verification (step 5)
      router.replace(`${ONBOARDING_ROUTE}/5`);
    } else {
      // Creator goes to subscription (step 4)
      router.replace(`${ONBOARDING_ROUTE}/4`);
    }
  };

  const handleClearSuggestions = () => {
    // Reload the page after clearing suggestions
    window.location.reload();
  };

  return (
    <div className="fc g30 p15 wf maw600 mx-auto mt-20 bg-background text-foreground rounded-xl shadow dark:shadow-white/10">
      <h1 className="fz24 fw700 tac">
        {isFan
          ? t("yourPreferences")
          : isCreator
          ? t("completeYourProfile")
          : t("accountDetails")}
      </h1>

      {/* Preferences note for fans */}
      {mongoUser?.profileType === "fan" && <PreferencesNote />}

      {/* Creator attributes note */}
      {mongoUser?.profileType === "creator" && <CreatorAttributesNote />}

      {/* Show auto-generated tags info for fans if tags exist - always show but with conditional opacity */}
      {isFan &&
        mongoUser.lastVisitedCreatorsTags &&
        (() => {
          const tags = getMostFrequentCreatorTags(
            mongoUser.lastVisitedCreatorsTags
          );
          const hasAny = tags.raceEthnicity || tags.hairColor || tags.bodyType;
          return (
            <>
              <div
                className={`fcc space-y-4 ${
                  userHasPreferences ? "opacity-20" : ""
                }`}
              >
                <div className="tac mb30">{t("auto")}</div>
                <TagProgressBar
                  value={Math.max(
                    mongoUser.lastVisitedCreatorsTags.raceEthnicity?.length ||
                      0,
                    mongoUser.lastVisitedCreatorsTags.hairColor?.length || 0,
                    mongoUser.lastVisitedCreatorsTags.bodyType?.length || 0
                  )}
                  max={MIN_VISITED_CREATOR_TAGS_FOR_SMART_MATCHING}
                />
                <AutoGeneratedTagsInfo tagsObj={tags} mongoUser={mongoUser} />
              </div>
              {!hasAny && (
                <div
                  className={`brand tac text-sm ${
                    userHasPreferences ? "opacity-20" : ""
                  }`}
                >
                  {t("visitAtleast")}{" "}
                  {MIN_VISITED_CREATOR_TAGS_FOR_SMART_MATCHING} {t("creators")}{" "}
                  {t("toEnableSmartMatching")}
                </div>
              )}
            </>
          );
        })()}
      {isCreator ? (
        <ProfileForm mongoUser={mongoUser} onSuccess={handleSuccess} />
      ) : (
        <>
          {/* FAN */}
          <div className="tac">{t("manual")}</div>
          <AccountForm mongoUser={mongoUser} onSuccess={handleSuccess} />
          <div className="text-center">
            <ClearAllSuggestionsButton
              currentUser={mongoUser}
              variant="outline"
              size="sm"
              className="text-sm underline cp"
              onSuccess={handleClearSuggestions}
            >
              {t("resetSuggestions") || "Reset suggestion preferences"}
            </ClearAllSuggestionsButton>
          </div>
        </>
      )}
    </div>
  );
}
